trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'terratamldacr.azurecr.io/snake-game'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'terratamldacr.azurecr.io/snake-game'
    dockerfile: 'Dockerfile'
    containerRegistry: 'acr-connection'
    tags: |
      $(Build.BuildId)

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'azure-service-connection'
    azureResourceGroup: 'terraform-aks'
    kubernetesCluster: 'terra-aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s-deployment.yaml'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'azure-service-connection'
    azureResourceGroup: 'terraform-aks'
    kubernetesCluster: 'terra-aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s-service.yaml'
