trigger:
  branches:
    include:
      - main

variables:
  containerRegistry: terratamldacr.azurecr.io
  imageName: snake-game
  imageTag: latest
  aksResourceGroup: terraform-aks
  aksClusterName: terra-aks
  azureSubscription: azure-service-connection

stages:
  - stage: Build
    jobs:
      - job: Build_Image_And_Test
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Building Docker image for Snake game..."
              docker build -t $(imageName):$(imageTag) .
            displayName: 'Build Docker Image'
          - script: |
              echo "Saving Docker image as tar file..."
              mkdir -p $(Build.ArtifactStagingDirectory)
              docker save $(imageName):$(imageTag) -o $(Build.ArtifactStagingDirectory)/$(imageName).tar
            displayName: 'Save Docker Image'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/$(imageName).tar'
              artifact: 'dockerImage'
            displayName: 'Publish Docker Image Artifact'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy_To_AKS
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'Fetch AKS Kubeconfig'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Fetching Kubernetes configuration using service connection..."
                az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName)
          - script: |
              echo "Logging into Docker registry..."
              docker login $(containerRegistry) -u $(registryUsername) -p $(registryPassword)
            displayName: 'Docker Login'
          - script: |
              echo "Creating Kubernetes secret for Docker registry credentials..."
              kubectl create secret docker-registry regcred \
                --docker-server=$(containerRegistry) \
                --docker-username=$(registryUsername) \
                --docker-password=$(registryPassword) \
                --dry-run=client -o yaml | kubectl apply -f -
            displayName: 'Create Kubernetes Secret'
          - script: |
              echo "Deploying to AKS using deployment manifest..."
              kubectl apply -f deployment.yml
            displayName: 'Deploy to AKS'
