apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      imagePullSecrets:
        - name: container-image-pull-secret
      containers:
        - name: snake-game
          image: snake-game:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
spec:
  selector:
    app: snake-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
