apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
  labels:
    app: nginx-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
      - name: nginx
        image: terratamldacr.azurecr.io/nginx-website:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-website
  labels:
    app: nginx-website
spec:
  selector:
    app: nginx-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
