apiVersion: v1
kind: Service
metadata:
  name: nginx-website-service
  labels:
    app: nginx-website
spec:
  type: LoadBalancer
  selector:
    app: nginx-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
