apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: snake-game
        image: myregistry.azurecr.io/snake-game:v1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
